### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by AlexD81** [Clybius/ComfyUI-Extra-Samplers#1]
Hi,   I've installed it with Manager.  
But it doen't work, the following error appears:
0.8 seconds (IMPORT FAILED): C:\Users\*******\ComfyUI\custom_nodes\ComfyUI-Extra-Samplers

![изображение](https://github.com/Clybius/ComfyUI-Extra-Samplers/assets/150659653/030bcf3e-87d7-454e-baa8-549ea7d743b9)

it's on windows

**Comment by Clybius** [comment]
If you scroll up in the console, there should be an error spit out while ComfyUI is loading. Do you happen to have a more detailed error log of the failed import?

Having checked the things I should off the top of my head, there is an extraneous import relating to scipy, which I will push a fix for within an hour. If that fixes it, let me know, otherwise that log would greatly help me further diagnose the failed import.

Sorry about the issue!

**Comment by AlexD81** [comment]
Hi Clybius,  hope it's necessary part of log

 File "C:\Users\Atlasiko\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Atlasiko\ComfyUI\custom_nodes\ComfyUI-Extra-Samplers\__init__.py", line 1, in <module>
    from . import extra_samplers
  File "C:\Users\Atlasiko\ComfyUI\custom_nodes\ComfyUI-Extra-Samplers\extra_samplers.py", line 599, in <module>
    from k_diffusion.sampling import sample_lcm
ImportError: cannot import name 'sample_lcm' from 'k_diffusion.sampling' (C:\Users\Atlasiko\AppData\Local\Programs\Python\Python310\lib\site-packages\k_diffusion\sampling.py)

Cannot import C:\Users\Atlasiko\ComfyUI\custom_nodes\ComfyUI-Extra-Samplers module for custom nodes: cannot import name 'sample_lcm' from 'k_diffusion.sampling' (C:\Users\Atlasiko\AppData\Local\Programs\Python\Python310\lib\site-packages\k_diffusion\sampling.py)

**Comment by blepping** [comment]
@AlexD81 if you change

```python
from k_diffusion.sampling import sample_lcm
```

to

```python
from comfy.k_diffusion.sampling import sample_lcm
```

in `extra_samplers.py` around line 599 does that fix the issue for you? 

(@Clybius is there a reason to use the package `k_diffusion_sampling` at all instead of the comfy version?)

**Comment by AlexD81** [comment]
Hello, there's no import error anymore,
however in log i see this

`C:\Users\A\ComfyUI\custom_nodes\ComfyUI-Extra-Samplers\nodes.py:251: SyntaxWarning: "is" with a literal. Did you mean "=="?
  samples = sampler.sample(model_wrap, temp_sigmas, extra_args, callback, noise.to(device) if i is 0 else torch.zeros(latent_image.size(), dtype=latent_image.dtype, layout=latent_image.layout, device=device), samples if samples is not None else latent_image, denoise_mask, True)
C:\Users\A\ComfyUI\custom_nodes\ComfyUI-Extra-Samplers\nodes.py:254: SyntaxWarning: "is" with a literal. Did you mean "=="?
  samples = sampler2.sample(model_wrap2, temp_sigmas2, extra_args2, callback2, noise.to(device2) if i is 0 else torch.zeros(latent_image.size(), dtype=latent_image.dtype, layout=latent_image.layout, device=device2), samples if samples is not None else latent_image, denoise_mask2, True)`

**Comment by blepping** [comment]
> however in log i see this

that shouldn't cause any issues, basically just a coding style thing since it's an integer value.
