### ISSUE TITLE
Request to add

### ISSUE THREAD

**Issue by JZZZ1314** [Clybius/ComfyUI-Extra-Samplers#7]
https://github.com/jabir-zheng/TCD/blob/main/scheduling_tcd.py

After reading the paper, it was found that this method significantly improves the generation quality

**Comment by Clybius** [comment]
Seems interesting, I'll keep looking into it.

My attempts to implement it so far haven't been successful (the latent will NaN by the second step, when gamma/eta > 0), but I'll keep tryin'.
